
mydata = read.csv(file.choose())
attach(mydata)
summary(mydata)
str(mydata)
show(mydata)
names(mydata)
boxplot(mydata)
teamname = c(rep("Dallas",17),rep("Greenbay",17),rep("Denver",17),rep("Miami",17),rep("Sanfrancisco",17))
teamweight = c(mydata$Dallas,mydata$Greenbay,mydata$Denver,mydata$Miami,mydata$Sanfrancisco)
newdata = data.frame(teamname,teamweight)
footbalannova = aov(teamweight~teamname,newdata)
summary(footbalannova)
TukeyHSD(footbalannova)
Rserve::Rserve()
install.packages("Rserve")
install.packages("pracma")
mydata = read.csv(file.choose())
attach(mydata)
summary(mydata)
str(mydata)
boxplot(mydata)
names(mydata)
SectorName = c(rep("Auto",15),rep("Bankex",15),rep("Energy",15),rep("HealthCare",15),rep("FMCG",15))
ClosingPrice = c(mydata$Auto,mydata$Bankex,mydata$Energy,mydata$HealthCare,mydata$FMCG)
newdata = data.frame(SectorName,ClosingPrice)
bseannova = aov(ClosingPrice~SectorName,newdata)
summary(bseannova)
TukeyHSD(bseannova)
